version: "3.7"

services:
  # react-app:
  #   image: react-app
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mern-app

  react-app-nginx:
    image: react-app-nginx
    stdin_open: true
    ports:
      - "8000:80"
    networks:
      - mern-app

  api:
    image: api
    ports:
      - "5000:5000"
    networks:
      - mern-app
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:3.6.22-xenial
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - mern-app
  #   volumes:
  #     - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
# volumes:
#   mongo-data:
#     driver: local
# docker-compose -up
